lat-dataset-path: ./latency_dataset/wmt14ende_cpu_raspberrypi_all.csv
feature-norm: [640, 6, 2048, 6, 640, 6, 2048, 6, 6, 2]
lat-norm: 5000
feature-dim: 10
hidden-dim: 400
hidden-layer-num: 3
ckpt-path: ./latency_dataset/predictors/wmt14ende_cpu_raspberrypi.pt
train-steps: 5000
bsz: 128
lr: 1e-5
